//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentWheels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRental
    {
        public int Id { get; set; }
        public string PhoneNo { get; set; }
        public string CustomerName { get; set; }
        public string CarNo { get; set; }
        public int Fees { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int TotalAmount { get; set; }
    
        public virtual CarDetail CarDetail { get; set; }
        public virtual RegisterDetail RegisterDetail { get; set; }
    }
}
