//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentWheels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisCount
    {
        public int Id { get; set; }
        public string CarNo { get; set; }
        public string ModelName { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> Offer { get; set; }
    
        public virtual CarDetail CarDetail { get; set; }
    }
}
