//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentWheels.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentWheelsEntities : DbContext
    {
        public RentWheelsEntities()
            : base("name=RentWheelsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarDetail> CarDetails { get; set; }
        public virtual DbSet<CarRental> CarRentals { get; set; }
        public virtual DbSet<CarReturn> CarReturns { get; set; }
        public virtual DbSet<RegisterDetail> RegisterDetails { get; set; }
        public virtual DbSet<RoleDetail> RoleDetails { get; set; }
    }
}
